name: push

on:
  push:
    branches:
      - main
      - 'v*'
    tags:
      - v1.15.[0-9]+-*
      - v1.16.[0-9]+-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Where am I?
        run: |
          echo 'main'
      - name: Getting image tag
        id: tag
        run: |
          if [ ${{ github.event_name == 'workflow_dispatch' }} ]; then
            tag=${{ inputs.tag }}
            tag=${tag##*/}-fips
          else
            echo ${GITHUB_REF}
            echo ${GITHUB_REF##*/}
            tag=${GITHUB_REF##*/}-fips
          fi
