on:
  push:
    tags:
      - 'hello/michi/v[0-9]+.[0-9]+.[0-9]+-hello'

name: release test

jobs:
  build:
    name: release test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get image tag
        id: tag
        run: |
          tag=${GITHUB_REF##*/}
          another_tag=$(echo $tag | cut -d "-" -f 1)
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "another-tag=$another_tag" >> $GITHUB_OUTPUT

      - name: Create a Release
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2
        with:
          name: ${{ steps.tag.outputs.tag }}
          tag_name: ${{ steps.tag.outputs.tag }}
          draft: true
          files: |
            my-innocent-program
          body: |
            # ${{ steps.tag.outputs.tag }} release

            Hello ${{ steps.tag.outputs.tag }}.

            Hello ${{ steps.tag.outputs.another-tag }}.
